swagger: "2.0"
info:
  version: "1.0.0"
  title: "Quizz movie"
host: "localhost:8090"
basePath: "/"
paths:
  /question:
    get:
      summary: "Get a new question"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Token"
        description: "The token of the user"
        required: true
        schema:
          $ref: "#/definitions/Token"
      responses:
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/Question"
        '405':
          description: "Invalid Token"
        '400':
          description: "Error not defined"
  /response:
    post:
      summary: "Verify an answers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Token"
        description: "The token of the user"
        required: true
        schema:
          $ref: "#/definitions/Token"
      responses:
        '200':
          description: "OK"
          schema:
            type: boolean
        '405':
          description: "Invalid Token"
        '400':
          description: "Error not defined"
  /login:
    post:
      summary: "Login a user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Login"
        description: "The login of the user"
        required: true
        type: "string"
      - in: "header"
        name: "Password"
        description: "The password of the user"
        required: true
        type: "string"
      responses:
        '200':
          description: "OK"
          schema:
            $ref: "#/definitions/Token"
        '401':
          description: "Login or password invalid"
  /register:
    post:
      summary: "Register a user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Login"
        description: "The future login of the user"
        required: true
        type: "string"
      - in: "header"
        name: "Password"
        description: "The future password of the user"
        required: true
        type: "string"
      responses:
        '200':
          description: "OK"
        '409':
          description: "Login already used"
  /disconnect:
    post:
      summary: "Disconnect user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Token"
        description: "The token of the user"
        required: true
        schema:
          $ref: "#/definitions/Token"
      responses:
        '200':
          description: "OK"
        '405':
          description: "Invalid Token"
  /goodanswers:
    get:
      summary: "Return the number of good answers of the user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Token"
        description: "The token of the user"
        required: true
        schema:
          $ref: "#/definitions/Token"
      responses:
        '200':
          description: "OK"
          schema:
            type: "string"
            example: "0"
        '405':
          description: "Invalid Token"
  /answers:
    get:
      summary: "Return the number of answers of the user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Token"
        description: "The token of the user"
        required: true
        schema:
          $ref: "#/definitions/Token"
      responses:
        '200':
          description: "OK"
          schema:
            type: "string"
            example: "0"
        '405':
          description: "Invalid Token"
definitions:
  Token:
    type: "object"
    required:
    - "token"
    properties:
      token:
        type: "string"
        example: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsb2dpbiJ9.7crGOpfi96uUsmDAZoPx-PAFktRU5vmQKIduEgx2PHz_K5NGC4uyvkX_PPDqS1_NZ2v9xJHtaWTQx8r-9Qa3zA"
  Question:
    type: "object"
    required:
    - "value"
    properties:
      question:
        type: "string"
        example: "When the movie XXX has been released?"
      poster:
        type: "string"
        example: "http://example.com/example.png"
